name: boero-staging

services:
  ui:
    container_name: boero-ui-staging

  api:
    container_name: boero-api-staging
    environment:
      SPRING_PROFILES_ACTIVE: staging

  redis:
    container_name: boero-redis-staging

  postgres:
    container_name: boero-postgres-staging

volumes:
  ui-next-cache:
    name: boero-ui-next-cache-staging
  postgres-data:
    name: boero-api-postgres-data-staging
  redis-data:
    name: boero-api-redis-data-staging
  api-logs:
    name: boero-api-logs-staging
  api-enrollment-storage:
    name: boero-api-enrollment-storage-staging

networks:
  default:
    name: boero-network-staging
