name: boero-production

services:
  ui:
    container_name: boero-ui-production

  api:
    container_name: boero-api-production
    environment:
      SPRING_PROFILES_ACTIVE: prod

  redis:
    container_name: boero-redis-production

  postgres:
    container_name: boero-postgres-production

volumes:
  ui-next-cache:
    name: boero-ui-next-cache-prod
  postgres-data:
    name: boero-api-postgres-data-prod
  redis-data:
    name: boero-api-redis-data-prod
  api-logs:
    name: boero-api-logs-prod

networks:
  default:
    name: boero-network-production
